[package]
name = "dsp-blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
jack = "0.13.0"
raylib = "5.0.1"
tidy-builder = { git="https://github.com/maminrayej/tidy-builder", branch="refactor" }
