[package]
name = "dsp-blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
raylib = "5.0.1"
rodio = "0.19.0"
tidy-builder = { git="https://github.com/maminrayej/tidy-builder", branch="refactor" }
